import { useQuery } from "convex/react";
import {
  AlertTriangle,
  ArrowLeft,
  BookOpen,
  Download,
  FileText,
  Loader2,
} from "lucide-react";
import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { api } from "../../convex/_generated/api";
import { chapters } from "../data/chapters";
import { canAccessChapter, getTierByName } from "../data/tiers";

export default function GeneratePage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const clientId = searchParams.get("client");
  const isAdmin = useQuery(api.admin.isAdmin);
  const clients = useQuery(api.admin.listClients);
  const [selectedClient, setSelectedClient] = useState(clientId || "");
  const [generating, setGenerating] = useState(false);
  const [generatedHtml, setGeneratedHtml] = useState<string | null>(null);

  if (!isAdmin) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh]">
        <p className="text-[#e8e6e1]/50">Admin access required.</p>
      </div>
    );
  }

  const client = clients?.find((c: any) => c._id === selectedClient);

  const handleGenerate = async () => {
    if (!selectedClient) return;
    setGenerating(true);

    // Build HTML Life Manual from client data
    try {
      const tier = client?.tier || "vault";
      const tierInfo = getTierByName(tier);
      const accessibleChapters = chapters.filter((ch) =>
        canAccessChapter(tier, ch.chapterNumber)
      );

      let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Life Manual - ${client?.userName || "Client"}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=Libre+Baskerville:wght@400;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Libre Baskerville', serif; background: #faf8f5; color: #1a1a1a; }
    .cover { page-break-after: always; height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; background: #0a0a0a; color: #d9cca0; padding: 2rem; }
    .cover h1 { font-family: 'Cinzel', serif; font-size: 2.5rem; letter-spacing: 0.1em; }
    .cover .subtitle { font-size: 0.9rem; opacity: 0.6; margin-top: 1rem; }
    .cover .client-name { font-family: 'Cinzel', serif; font-size: 1.5rem; margin-top: 3rem; }
    .cover .tier { font-size: 0.8rem; opacity: 0.5; margin-top: 0.5rem; text-transform: uppercase; letter-spacing: 0.2em; }
    .chapter { page-break-before: always; padding: 2rem; }
    .chapter h2 { font-family: 'Cinzel', serif; font-size: 1.5rem; margin-bottom: 0.5rem; border-bottom: 2px solid #d9cca0; padding-bottom: 0.5rem; }
    .chapter .desc { font-size: 0.85rem; color: #666; margin-bottom: 1.5rem; }
    .section { margin-bottom: 1.5rem; }
    .section h3 { font-family: 'Cinzel', serif; font-size: 1.1rem; color: #333; margin-bottom: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 0.8rem; }
    th { background: #f5f3f0; font-family: 'Cinzel', serif; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }
    .empty { color: #999; font-style: italic; }
    .footer { text-align: center; font-size: 0.7rem; color: #999; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; }
  </style>
</head>
<body>
  <div class="cover">
    <h1>LIFE MANUAL</h1>
    <p class="subtitle">Legacy Architect RVA</p>
    <p class="client-name">${client?.userName || "Client"}</p>
    <p class="tier">${tierInfo?.name || tier} Edition</p>
  </div>
`;

      for (const ch of accessibleChapters) {
        html += `
  <div class="chapter">
    <h2>Chapter ${ch.chapterNumber}: ${ch.title}</h2>
    <p class="desc">${ch.description}</p>
`;
        for (const sec of ch.subSections) {
          html += `    <div class="section"><h3>${sec.title}</h3>`;
          if (sec.tableColumns && sec.tableColumns.length > 0) {
            html += `<table><thead><tr>`;
            for (const col of sec.tableColumns) {
              html += `<th>${col.label}</th>`;
            }
            html += `</tr></thead><tbody>`;
            html += `<tr><td colspan="${sec.tableColumns.length}" class="empty">Data loaded from client portal</td></tr>`;
            html += `</tbody></table>`;
          }
          html += `</div>`;
        }
        html += `  </div>`;
      }

      html += `
  <div class="footer">
    <p>Generated by Legacy Architect RVA &middot; ${new Date().toLocaleDateString()}</p>
    <p>This document contains sensitive information. Handle with care.</p>
  </div>
</body>
</html>`;

      setGeneratedHtml(html);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!generatedHtml) return;
    const blob = new Blob([generatedHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `life-manual-${client?.userName?.replace(/\s+/g, "-").toLowerCase() || "client"}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
      <button
        onClick={() => navigate("/admin")}
        className="flex items-center gap-2 text-sm text-[#e8e6e1]/60 hover:text-gold-primary transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Admin
      </button>

      <div>
        <h1 className="font-heading text-3xl text-gold-gradient">Generate Life Manual</h1>
        <p className="text-[#e8e6e1]/50 mt-2">
          Generate a formatted Life Manual for a client. The manual includes all completed data
          from their portal organized by chapter.
        </p>
      </div>

      {/* Client Selection */}
      <div className="bg-[#0a0a0a] rounded-xl border border-gold-border p-5 space-y-4">
        <div>
          <label className="text-xs text-[#e8e6e1]/50 uppercase tracking-wider font-heading">Select Client</label>
          <select
            value={selectedClient}
            onChange={(e) => {
              setSelectedClient(e.target.value);
              setGeneratedHtml(null);
            }}
            className="w-full bg-black border border-gold-border/40 rounded-lg px-3 py-2.5 text-sm text-[#e8e6e1] focus:border-gold-primary/50 focus:outline-none mt-1 appearance-none cursor-pointer"
          >
            <option value="">Choose a client...</option>
            {clients?.map((c: any) => (
              <option key={c._id} value={c._id}>
                {c.name} ({c.email}) - {getTierByName(c.tier)?.name ?? c.tier}
              </option>
            ))}
          </select>
        </div>

        {selectedClient && (
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="flex items-center gap-2 bg-gradient-to-r from-[#d9cca0] to-[#b89f6b] text-[#0a0a0a] font-heading text-sm font-semibold px-5 py-2.5 rounded-lg hover:opacity-90 transition-opacity disabled:opacity-50"
          >
            {generating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <BookOpen className="w-4 h-4" />
            )}
            {generating ? "Generating..." : "Generate Manual"}
          </button>
        )}
      </div>

      {/* Generated Manual */}
      {generatedHtml && (
        <div className="bg-[#0a0a0a] rounded-xl border border-gold-border p-5 space-y-4">
          <div className="flex items-center gap-2 text-gold-primary">
            <FileText className="w-5 h-5" />
            <h3 className="font-heading text-lg">Manual Generated</h3>
          </div>
          <p className="text-sm text-[#e8e6e1]/50">
            Life Manual for {client?.userName} has been generated. Download the HTML file,
            then open it in a browser and print to PDF for a polished output.
          </p>
          <div className="flex gap-3">
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 bg-gradient-to-r from-[#d9cca0] to-[#b89f6b] text-[#0a0a0a] font-heading text-sm font-semibold px-5 py-2.5 rounded-lg hover:opacity-90 transition-opacity"
            >
              <Download className="w-4 h-4" /> Download HTML
            </button>
          </div>

          <div className="bg-black rounded-lg border border-gold-border/20 p-3 flex items-start gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-400 mt-0.5 shrink-0" />
            <p className="text-xs text-[#e8e6e1]/60">
              After delivery, all files and access are purged. Your information stays with you.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
